### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by chanrxia** [orzubalsky/creative-computing-2018#18]
Are we allowed to change the sizes of our word images via code?

**Comment by albertparson** [comment]
I feel like you can, I honestly want to do the same thing so I would say go fo it.

**Comment by orzubalsky** [comment]
Yes, if you feel comfortable doing it you should go for it! It's definitely not required. 

You can set the dimensions of an image with css: 
```css
img {
    width: 100px;
    height: 100px;
}

.some-image-class {
    width: 100px;
    height: 100px;
}

#some-image-id {
    width: 100px;
    height: 100px;
}
```

If you want to maintain the aspect ratio of the image without skewing it, try including `object-fit: contain;` or `object-fit: cover;`
